### ISSUE TITLE
Uninformative error if postresql is not installed

### ISSUE THREAD

**Issue by dpyro** [ArkEcosystem/ark-node#39]
Running `npm install` or `yarn` after freshly cloning ark-node results in:

```
> libpq@1.8.7 install /Users/${USER}/src/ark-node/node_modules/libpq
> node-gyp rebuild

/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sumantmanne/src/ark-node/node_modules/libpq
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

On macOS this is resolved with `brew install postgresql`.

## Fix

An informative error should be displayed if no postgresql installation is found.

**Comment by CruelSamaritan** [comment]
Dude, you saved my day! Thanks a lot!

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
