### ISSUE TITLE
Possible issue with Postgres

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/ark-node#45]
For reference so I can take a look. My node stopped completely, logging the below message. It was still trying to receive blocks. Restarting Ark (R in ARKcommander) fixed the issue and it started syncing again.

```
[ERR] 2017-11-15 11:53:51 | stack - Error: Unable to set non-blocking to true
    at Client.dispatchQuery (/home/alex/ark-node/node_modules/pg-native/index.js:196:26)
    at Client.query (/home/alex/ark-node/node_modules/pg-native/index.js:214:8)
    at NativeQuery.submit (/home/alex/ark-node/node_modules/pg/lib/native/query.js:128:17)
    at Client._pulseQueryQueue (/home/alex/ark-node/node_modules/pg/lib/native/index.js:171:9)
    at Client.query (/home/alex/ark-node/node_modules/pg/lib/native/index.js:130:8)
    at /home/alex/ark-node/node_modules/pg-promise/lib/query.js:135:27
    at promise (/home/alex/ark-node/node_modules/pg-promise/lib/promise.js:22:20)
    at Database.$query (/home/alex/ark-node/node_modules/pg-promise/lib/query.js:124:12)
    at Database.<anonymous> (/home/alex/ark-node/node_modules/pg-promise/lib/query.js:227:23)
    at /home/alex/ark-node/node_modules/pg-promise/lib/database.js:238:42
```

```
KiB Mem :  1999040 total,   139376 free,   433004 used,  1426660 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  1330008 avail Mem
```

```
Filesystem      Size  Used Avail Use% Mounted on
udev            968M     0  968M   0% /dev
tmpfs           196M   13M  183M   7% /run
/dev/sda1       9.7G  5.7G  4.0G  59% /
tmpfs           977M  4.0K  977M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           977M     0  977M   0% /sys/fs/cgroup
tmpfs           196M     0  196M   0% /run/user/1001
```

```
root@vps456227:/home/alex# pg_isready
/var/run/postgresql:5432 - accepting connections
root@vps456227:/home/alex# /etc/init.d/postgresql status
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2017-11-15 07:00:15 CET; 5h 58min ago
  Process: 23772 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 23772 (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/postgresql.service

Nov 15 07:00:15 vps456227 systemd[1]: Starting PostgreSQL RDBMS...
Nov 15 07:00:15 vps456227 systemd[1]: Started PostgreSQL RDBMS.
```

**Comment by vitaly-t** [comment]
This library should upgrade `pg-promise` dependency from v5 to v7 ;)

**Comment by alexbarnsley** [comment]
Thanks @vitaly-t - how'd you get notified of this issue? 😆 

@fix is a pg-promise upgrade on the cards? To be honest, I only posted the above because it just happened. I've seen no one else have the same issue. It's only since the last node update that I got this, but I don't know how relevant that is.

**Comment by vitaly-t** [comment]
What I suggested isn't a fix, just a good/prudent starting point ;) but who knows, may be it is indeed related to the issue.

The underlying driver `node-postgres` was known to have issues over some Node updates that were sorted later.

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
